name: build-and-publish-on-tag

on:
  push:
    tags:
      - '*'

jobs:

  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Replace __version__
        run: sed -i -e "s/__version__ =.*/__version__ = '${RELEASE_VERSION}'/"
      - uses: stefanzweifel/git-auto-commit-action@v4
      - name: Push __version__ update
        with:
          commit_message: Bump version to ${RELEASE_VERSION}
          file_pattern: pteronode.py

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JackMcKew/pyinstaller-action-linux@main
      - name: PyInstaller Linux
        with:
          path: .
      - uses: JackMcKew/pyinstaller-action-windows@main
      - name: PyInstaller Windows
        with:
          path: .

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Create release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args:
            - dist/**/pteronode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}