name: build-and-publish-on-tag

on:
  push:
    tags:
      - '*'

jobs:

  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Replace __version__
        run: sed -i -e "s/__version__ =.*/__version__ = '${RELEASE_VERSION}'/" pteronode.py
      - name: Push __version__ update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump version to ${RELEASE_VERSION}
          file_pattern: pteronode.py

  build-and-release:
    runs-on: ubuntu-latest
    needs: [update-version]
    steps:
      - uses: actions/checkout@v2
      - name: PyInstaller Linux
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: .
          spec: linux_build.spec
      - uses: actions/upload-artifact@v2
        with:
          name: pteronode-linux
          path: dist
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: windows_build.spec
      - uses: actions/upload-artifact@v2
        with:
          name: pteronode-windows
          path: dist
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          gzip: false
          files: >
            dist/linux/pteronode/pteronode
            dist/windows/pteronode/pteronode.exe